feat(footer): better links
joint-online-judge/cattle pull request #38
Opened 2021-07-12 16:03 UTC by BoYanZh

2021-07-27 05:26 UTC, nichujie requested changes

2021-07-27 05:26 UTC, nichujie commented on src/components/Footer/FooterLinks.tsx
> +  external: boolean;
可选，默认false

2021-07-27 05:30 UTC, nichujie requested changes

2021-07-27 05:30 UTC, nichujie commented on src/components/Footer/FooterLinks.tsx
> +    external: false,
这里为啥都是false呢

2021-07-27 10:35 UTC, BoYanZh commented on src/components/Footer/FooterLinks.tsx
> +    external: false,
好像确实可以用`<Link>`

2021-07-31 07:20 UTC, nichujie approved these changes

2021-07-31 07:20 UTC, merged